language: java

jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
 - chmod +x gradlew
 - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew clean build -i --continue